title: Cornie en Sussie Alant
description: Cornie en Sussie Alant in Port Nolloth
sitename: Alant Seehuis
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
